
module Quizes
    Quizes = {
        'first_quiz' => {
            name: 'First Quiz',
            questions: [
                {
                    text: 'What type of platform is K9 Finance?',
                    wrong_answers: [
                        'A social media platform',
                        'A gaming platform',
                        'A news aggregation site'
                    ],
                    correct_answer: 'A liquid staking derivative platform'
                },
                {
                    text: 'Which blockchain does K9 Finance operate on?',
                    wrong_answers: [
                        'Ethereum',
                        'Bitcoin',
                        'Polkadot'
                    ],
                    correct_answer: 'Shibarium'
                },
                {
                    text: 'What token do $KNINE holders earn as rewards for validating blocks?',
                    wrong_answers: [
                        '$ETH',
                        '$SHIB',
                        '$USDT'
                    ],
                    correct_answer: '$BONE'
                },
                {
                    text: 'What is the name of the DAO governing K9 Finance?',
                    wrong_answers: [
                        'Council of Wolves',
                        'DeFi Alliance',
                        'Shiba Inu Committee'
                    ],
                    correct_answer: 'Roundtable of Dogs'
                },
                {
                    text: 'What is $knBONE?',
                    wrong_answers: [
                        'A new cryptocurrency',
                        'A non-transferable token',
                        'A payment method  '
                    ],
                    correct_answer: 'A derivative of $BONE that is freely transferable'
                },
                {
                    text: 'What benefit does liquid staking provide to users?',
                    wrong_answers: [
                        'Users lose access to staked tokens',
                        'Users must wait long periods to access funds',
                        'Users are forced to trade tokens'
                    ],
                    correct_answer: 'Users can use staked tokens while earning rewards'
                },
                {
                    text: 'What does the $KNINE token primarily govern?',
                    wrong_answers: [
                        'Trading strategies',
                        'Social media interactions',
                        'Market trends'
                    ],
                    correct_answer: "K9 Finance's direction and treasury"
                },
                {
                    text: 'What is the main advantage of using $knBONE in other DeFi applications?',
                    wrong_answers: [
                        'It cannot be used anywhere else',
                        'It provides additional staking rewards',
                        'It decreases the value of staked tokens  '
                    ],
                    correct_answer: 'It acts as collateral and can be used for lending'
                },
                {
                    text: 'What is the main focus of K9 Finance?',
                    wrong_answers: [
                        'Creating NFTs',
                        'Developing gaming solutions',
                        'Building a social network  '
                    ],
                    correct_answer: 'Supporting the Shibarium ecosystem'
                },
                {
                    text: 'What is a key problem with traditional PoS staking that K9 Finance addresses?',
                    wrong_answers: [
                        'High transaction fees',
                        'Lack of liquidity',
                        'Insufficient rewards'
                    ],
                    correct_answer: 'Users losing access to staked tokens'
                },
                {
                    text: 'What does "Real Yield" refer to in the context of K9 Finance?',
                    wrong_answers: [
                        'Yield from speculative trading',
                        'Yield generated by a centralized exchange',
                        'Yield from borrowing funds'
                    ],
                    correct_answer: 'DeFi yield from a true on-chain revenue source'
                },
                {
                    text: 'How does K9 Finance simplify the staking process?',
                    wrong_answers: [
                        'By requiring advanced technical knowledge',
                        'By limiting the number of tokens that can be staked',
                        'By requiring users to trade tokens constantly  '
                    ],
                    correct_answer: 'By eliminating hardware setup and maintenance'
                },
                {
                    text: 'How does K9 Finance allow for smaller deposits in staking?',
                    wrong_answers: [
                        'By enforcing minimum deposit amounts',
                        'By limiting access to certain users',
                        'By requiring multiple transactions'
                    ],
                    correct_answer: 'By providing rewards on any deposit size'
                },
                {
                    text: 'What allows K9 Finance to potentially expand outside of the Shibarium ecosystem?',
                    wrong_answers: [
                        'Its centralization model',
                        'The lack of community involvement',
                        'Its focus solely on Shibarium'
                    ],
                    correct_answer: 'The governance process of the DAO'
                }
            ]
        }
    }
end